# Generated by Django 5.2.1 on 2025-11-15 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_participant_budget_participant_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='description',
        ),
        migrations.AddField(
            model_name='organizer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed (E.164 format).", regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
