# Generated by Django 5.2.1 on 2025-11-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_organizer_description_organizer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moderation_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
